repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Check
        entry: uv run ruff check --fix
        language: system
        types: [python]
        require_serial: true
        stages: [pre-commit]

      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format
        language: system
        types: [python]
        require_serial: true
        stages: [pre-commit]

      - id: commitizen
        name: Commitizen check
        entry: uv run cz check --commit-msg-file
        language: system
        stages: [commit-msg]
